@startuml

class Timer {
    private boolean finished = false;
    private boolean running = false;
    private boolean started = false;

    private float timePassed = 0;
    private float goalTime = 0;

    public Timer(float goalTime)

    public void update(float delta)

    public float getTimePassed()

    public void start()

    public void stop()

    public boolean isRunning()

    public void restart()

    public boolean isStarted()

    public boolean isFinished()

}






class SetupGame {

    public final static int width = 1100;
    public final static int height = 700;
    public final static int fps = 60;
    public final static String path;
    public final static String pathMusic
    public static Music entryMusic;
    public static Music levelMusic;
    public static Music level1Music;
    public static Music level2Music;
    public static Music level3Music;
    public static Music level4Music;
    public static Music level5Music;
    public static Music gameOverMusic;
    public static Music winMusic;
    public static Sound hitSound;
    public static Sound throwSound;
    public static Sound coronaSound;
    public static Sound doctorSound;
    public static Sound windowSound;
    public static Sound doorSound;
    public static Sound pickSound;
    public static Sound teleportSound;


    public static Sound pickedSymbol;

    public void initMusic()

    public SetupGame(String name)

    public void initStatesList(GameContainer gameContainer) throws SlickException

    public static void main(String[] args) throws SlickException
}




@enduml